server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/bookcrud
    password: 
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect